### ISSUE TITLE
Inspector breaks server VMs

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#459]
### Expected Behavior

Using the Chrome Inspector to diagnose guest code issues should always be supported.

### Actual Behaviour

When activating the Chrome Inspector in tandem with a server VM, a crash occurs.

### Stacktrace

```
Caused by: org.graalvm.polyglot.PolyglotException: java.lang.IllegalStateException: Cannot write to stubbed stream from inside a guest VM.
        at elide.runtime.gvm.internals.context.NativeContextManagerImpl$StubbedOutputStream.write(NativeContextManagerImpl.kt:150)
        at java.base/java.io.OutputStream.write(OutputStream.java:167)
        at org.graalvm.truffle/com.oracle.truffle.api.impl.DispatchOutputStream.write(DispatchOutputStream.java:132)
        at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:313)
        at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:409)
        at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:414)
        at java.base/sun.nio.cs.StreamEncoder.lockedFlush(StreamEncoder.java:218)
        at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:205)
        at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:263)
        at java.base/java.io.BufferedWriter.implFlush(BufferedWriter.java:372)
        at java.base/java.io.BufferedWriter.flush(BufferedWriter.java:359)
        at java.base/java.io.PrintWriter.implNewLine(PrintWriter.java:659)
        at java.base/java.io.PrintWriter.newLine(PrintWriter.java:649)
        at java.base/java.io.PrintWriter.println(PrintWriter.java:808)
        at java.base/java.io.PrintWriter.println(PrintWriter.java:1006)
        at com.oracle.truffle.tools.chromeinspector.instrument.InspectorInstrument$Server.<init>(InspectorInstrument.java:439)
        at com.oracle.truffle.tools.chromeinspector.instrument.InspectorInstrument.onCreate(InspectorInstrument.java:227)
        at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.TruffleInstrument$Env.onCreate(TruffleInstrument.java:669)
        at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler$InstrumentClientInstrumenter.create(InstrumentationHandler.java:2226)
        at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentationHandler.createInstrument(InstrumentationHandler.java:269)
        at org.graalvm.truffle/com.oracle.truffle.api.instrumentation.InstrumentAccessor$InstrumentImpl.createInstrument(InstrumentAccessor.java:123)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotInstrument.ensureCreated(PolyglotInstrument.java:185)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.ensureInstrumentsCreated(PolyglotEngineImpl.java:697)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.createInstruments(PolyglotEngineImpl.java:691)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotEngineImpl.<init>(PolyglotEngineImpl.java:337)
        at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.buildEngine(PolyglotImpl.java:283)
        at com.oracle.graal.graal_enterprise/com.oracle.truffle.polyglot.enterprise.EnterprisePolyglotImpl.buildEngine(stripped:136)
        at org.graalvm.sdk/org.graalvm.polyglot.Engine$Builder.build(Engine.java:681)
        at elide.runtime.gvm.internals.context.NativeContextManagerImpl.<init>(NativeContextManagerImpl.kt:379)
        at elide.runtime.gvm.internals.context.$NativeContextManagerImpl$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1693)
        at io.micronaut.context.AbstractBeanResolutionContext.getBean(AbstractBeanResolutionContext.java:89)
        at io.micronaut.context.AbstractInitializableBeanDefinition.resolveBean(AbstractInitializableBeanDefinition.java:2165)
        at io.micronaut.context.AbstractInitializableBeanDefinition.getBeanForConstructorArgument(AbstractInitializableBeanDefinition.java:1328)
        at elide.runtime.gvm.$VMFacadeFactory$Definition.instantiate(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.resolveByBeanFactory(DefaultBeanContext.java:2307)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2277)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2289)
        at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3056)
        at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:81)
        at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2958)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2919)
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2730)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1756)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1731)
        at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:856)
        at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:346)
        at elide.server.ssr.ServerSSRRenderer$renderSuspendAsync$2$1$1.invokeSuspend(ServerSSRRenderer.kt:120)
        at elide.server.ssr.ServerSSRRenderer$renderSuspendAsync$2$1$1.invoke(ServerSSRRenderer.kt)
        at elide.server.ssr.ServerSSRRenderer$renderSuspendAsync$2$1$1.invoke(ServerSSRRenderer.kt)
        at elide.server.ssr.ServerSSRRenderer.prepareContext$server(ServerSSRRenderer.kt:72)
        at elide.server.ssr.ServerSSRRenderer$prepareContext$1.invokeSuspend(ServerSSRRenderer.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### Steps To Reproduce

1. Setup an Elide JVM server
2. Run it, and pass `-Delide.vm.inspect=true`
3. Observe error

### Environment Information

N/A

### Runtime

Native, JVM

### Language

JavaScript

### Version

1.0.0-alpha7

**Comment by sgammon** [comment]
Circumventing stubbed streams produces:
```
15:49:58.453 [io.micronaut.http.server.RouteExecutor] ERROR elide - Unexpected error occurred: Option inspect is an engine level instrument option. Engine level instrument options can only be configured for contexts without an explicit engine set. To resolve this, configure the option when creating the Engine or create a context without a shared engine.
java.lang.IllegalArgumentException: Option inspect is an engine level instrument option. Engine level instrument options can only be configured for contexts without an explicit engine set. To resolve this, configure the option when creating the Engine or create a context without a shared engine.
```
