### ISSUE TITLE
Known issues with Ruby

### ISSUE THREAD

**Issue by sgammon** [elide-dev/elide#789]
### Expected Behavior

1. Running Ruby on Elide should work

### Actual Behaviour

1. It crashes immediately instead

### Stacktrace

```
elide.tool.cli.err.AbstractToolError$Known: Error: LANGUAGE_NOT_SUPPORTED.
	at elide.tool.cli.err.AbstractToolError$Companion.forCase(AbstractToolError.kt:94)
	at elide.tool.cli.err.AbstractToolError$Companion.forCase$default(AbstractToolError.kt:89)
	at elide.tool.cli.err.ToolErrorCase.raise(ToolErrorCase.kt:29)
	at elide.tool.cli.err.ToolErrorCase.raise$default(ToolErrorCase.kt:28)
	at elide.tool.cli.err.ToolErrorCase.asError(ToolErrorCase.kt:35)
	at elide.tool.cli.cmd.repl.ToolShellCommand.invoke(ToolShellCommand.kt:1584)
	at elide.tool.cli.cmd.repl.ToolShellCommand$invoke$1.invokeSuspend(ToolShellCommand.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at elide.tool.cli.AbstractToolCommand.execute(AbstractToolCommand.kt:130)
	at elide.tool.cli.AbstractToolCommand.call(AbstractToolCommand.kt:154)
	at elide.tool.cli.AbstractToolCommand.run(AbstractToolCommand.kt:165)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at elide.tool.cli.ElideTool$Companion.exec$cli(ElideTool.kt:168)
	at elide.tool.cli.ElideTool$Companion.main$lambda$2(ElideTool.kt:138)
	at elide.tool.cli.ElideTool$Companion.installStatics$lambda$1(ElideTool.kt:123)
	at elide.tool.cli.ElideTool$Companion.installStatics(ElideTool.kt:131)
	at elide.tool.cli.ElideTool$Companion.main(ElideTool.kt:137)
	at elide.tool.cli.ElideTool.main(ElideTool.kt)
elide 20:56:45.938 ERROR Execution failed with code 1 due to Error: LANGUAGE_NOT_SUPPORTED.
elide 20:56:45.939 ERROR Stacktrace:
elide.tool.cli.err.AbstractToolError$Known: Error: LANGUAGE_NOT_SUPPORTED.
	at elide.tool.err.ErrorHandler$ErrorUtils.buildStacktrace(ErrorHandler.kt:96)
	at elide.tool.err.ErrorHandler.getExitCode(ErrorHandler.kt:651)
	at picocli.CommandLine.mappedExitCode(CommandLine.java:1239)
	at picocli.CommandLine.handleUnhandled(CommandLine.java:2191)
	at picocli.CommandLine.execute(CommandLine.java:2182)
	at elide.tool.cli.ElideTool$Companion.exec$cli(ElideTool.kt:168)
	at elide.tool.cli.ElideTool$Companion.main$lambda$2(ElideTool.kt:138)
	at elide.tool.cli.ElideTool$Companion.installStatics$lambda$1(ElideTool.kt:123)
	at elide.tool.cli.ElideTool$Companion.installStatics(ElideTool.kt:131)
	at elide.tool.cli.ElideTool$Companion.main(ElideTool.kt:137)
	at elide.tool.cli.ElideTool.main(ElideTool.kt)
```

### Steps To Reproduce

1. Use Ruby on Elide, observe error

### Environment Information

Everywhere

### Runtime

Native

### Language

Ruby

### Version

1.0.0-alpha7

**Comment by sgammon** [comment]
filed upstream and described in detail at oracle/graal#8795
